# where to place it: ~/.config/snakemake/profile/config.yaml

#jobscript: "grid-jobscript.sh"   # optional, only needed if you want a wrapper for the jobs
executor: "htcondor"           
default_resources: 
  cpus: "{threads}"
  mem_mb: 3000
  disk_mb: 10000
  runtime: 3600 # 3600s1h, 900s = 15min. 
htcondor-jobdir: "/user/abiolchi/muraves_outputs"  # directory for htcondor jobs

use-singularity: true
singularity-args: "--cleanenv -B $HOME/Software -B $HOME/muraves_outputs -B /tmp:/workspace/tmp -B /pnfs/iihe/muraves/muraves_DATA" #user $HOME is automatically binded by si

max-jobs-per-second: 100
max-status-checks-per-second: 1
seconds-between-status-checks: 120
restart-times: 0
local-cores: 1
jobs: 250
cores: {threads}
verbose: False
