# Path where RAW_GZ folder is located. Here all the outputs will be saved.
# For production on T2B -> data_path: "/pnfs/iihe/muraves/muraves_DATA/"

#-----------processing parameters-----------------
data_path: '/user/abiolchi/Software/test_data' # Path where data are stored ['/data',"/pnfs/iihe/muraves/muraves_DATA", ...]. 
# This should be the path recongnised by the condor node or the container where the code is executed.

#scratch_path: "$TMPDIR" 
# temporary folder for intermediate files: it will be deleted at the end of the execution
# it works on condor node, working node or on your local laptop.

copy_to_data: False 
# True:  temporary files will be copied to the data_path at the end of the execution, and deleted from the scratch_path
# False: they will be copied into your home directory $HOME/muraves_outputs, and deleted from the scratch_path

batch_size: 1 # number of runs to be executed in parallel.
threads: 1 # number of cores requested per rule.


#-----------selection parameters-----------------
hodoscope:
  #- BLU 
  - NERO

type:
  #- ADC or PIEDISTALLI
  - ADC

batch_idx: 
  #"0-100" # batch of runs to be executed. It can be specified as:

run:
  # A-B: execute from A to B
  #2402-2412
  # NERO highest run is 12104
  # ROSSO highest run is 15012
  # BLU highest run is 10011

  # A,B execute A and B
  #2500,2509
  
  # A: execute A
  "2500"


logs_on_console: False #(True/False)
verbose: info # (debug/info/warning/error/critical)
overwrite_outputs: True # (True/False) if True, existing output files will be overwritten. If False, existing output files will be kept and the corresponding runs will be skipped.

#-----------execution configuration files-----------------
execution_config:
  reco_parameters_file: "muraves_cfg_files/reco_parameters.json"
  # Optional override file merged on top of reco_parameters_file. Leave empty to disable.
  reco_override_file: ""
  spiroc_mapping_file: "muraves_cfg_files/spiroc-hybrid-map.cfg"
  telescope_cfg_template: "muraves_cfg_files/telescope{color}.cfg"

