configfile: 'config.yaml'
configfile: '../../tag/requirements.yaml'
import os
import multiprocessing
from muraves_lib import snakefile_helper
# IMPROVEMENTS:
# The number of boards and channel should go in another configuration file

#>>>>>~~~~~~~~~~~~~~~~~~ GLOBAL PARAMETERS  ~~~~~~~~~~~~~~~~~~~
PNFS = config['data_path']
HOME = os.path.expandvars('/user/abiolchi/muraves_outputs')
BATCH_SIZE = config['batch_size'] 
THREADS = config['threads']
if config['run']:
    runs = snakefile_helper.parse_runs(config['run'])  # convert config file format into list of runs.
    BATCHES = list(snakefile_helper.batch_runs(runs, BATCH_SIZE))  # # create batches: [[2500,2501,2502], [2503,2504,2505], ...]
    BATCH_IDX = range(len(BATCHES))
else:
    BATCH_IDX = snakefile_helper.parse_batch_indices(config['batch_idx'])
overwrite_outputs=config['overwrite_outputs'],
log_on_console=config['logs_on_console'],
verbose=config['verbose'],
#<<<<<~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

localrules: all

rule all:
    input:
        expand(
            '{output_path}/PEDESTAL/{color}/{version}/PIEDISTALLI_batch{batch_idx}.stamp',
            output_path=PNFS if config.get('copy_to_data') else HOME,
            color=config['hodoscope'],
            version=config['version'],
            #type=config['type'], 
            ## NB: this isn't needed anymore if rule all want's to produce output of pedestal rule or analysis rule, as in this case the dependance is explicit.
            batch_idx=BATCH_IDX
        )


rule parse_batch:
    threads: THREADS
    container: '/user/abiolchi/muraves-sing.sif'
    input:
        script="1_Parser/prep.py"
    params:
        raw_data_path=f'{PNFS}/RAW_GZ/{{color}}',
        runs=lambda wildcards:
            ( BATCHES[int(wildcards.batch_idx)] if config.get('run')
                else list(range(int(batch_idx) * BATCH_SIZE, int(wildcards.batch_idx) * BATCH_SIZE + BATCH_SIZE))
            ),  
    output:
        output_filename="{output_path}/PARSED/{color}/{version}/{type}_batch{batch_idx}.stamp" #Questo output contiene la lista dei file prodotti dal batch, che saranno usati come input per le regole successive.
    shell:
        "python {input.script} -i {params.raw_data_path} -th {threads} -t {wildcards.type} -r {params.runs} -o {output.output_filename} -l {log_on_console} -v {verbose} -ow {overwrite_outputs}"

rule prereco:
    threads: THREADS
    container: '/user/abiolchi/muraves-sing.sif'
    input:
        script = '2_PreRec/MakePedestalTree.py',
        input_filename = "{output_path}/PARSED/{color}/{version}/{type}_batch{batch_idx}.stamp"
    params:
        nBoards = 16,
        nInfoBoard = 39,
        nChannels= 32
    output:
        output_filename = "{output_path}/PRERECONSTRUCTED/{color}/{version}/{type}_batch{batch_idx}.stamp"
    shell: "python {input.script} -i {input.input_filename} -info {params.nBoards} {params.nInfoBoard} {params.nChannels} -o {output.output_filename} -th {threads} -l {log_on_console} -v {verbose} -ow {overwrite_outputs}"



rule pedestal_analysis:
    threads: THREADS
    container: '/user/abiolchi/muraves-sing.sif'
    input:
        script = '3_PedAna/OnePhE_evaluator.py',
        input_filename = '{output_path}/PRERECONSTRUCTED/{color}/{version}/PIEDISTALLI_batch{batch_idx}.stamp'
    params: # to be removed at next version
        nBoards = 16,
        nInfoBoard = 39,
        nChannels= 32,
        overwrite_outputs = "True"

    #    number_of_runs = 1
    #    delta_around_central_runID = 0
    output:
        output_filename = "{output_path}/PEDESTAL/{color}/{version}/PIEDISTALLI_batch{batch_idx}.stamp",
        #sub_files = 
        #expand(
        #    "{{output_path}}/PEDESTAL/{{color}}/{{version}}/{run}/pedestal_{n}.cfg", run = lambda wildcards:
        #    ( BATCHES[int(wildcards.batch_idx)] if config.get('run')
        #        else list(range(int(batch_idx) * BATCH_SIZE, int(wildcards.batch_idx) * BATCH_SIZE + BATCH_SIZE))
        #    ),   n = range(16)
        #) ##NB: CONS--> these subruns will remain silents, the success has to be checks through logs 
    shell: "python {input.script} -i {input.input_filename} -info {params.nBoards} {params.nInfoBoard} {params.nChannels} -o {output.output_filename} -th {threads} -l {log_on_console} -v {verbose} -ow {params.overwrite_outputs}"



#rule analyse:
#    input:
#        main_script = "4_MainRecSof/MURAVES_reco_v2.cpp",
#        script_1 = "4_MainRecSof/ClusterLists.cc",
#        script_2 =  "4_MainRecSof/EvaluateAngularCoordinates.cc",
#        script_3 = "4_MainRecSof/ReadEvent.cc",
#        script_4 = "4_MainRecSof/Tracking.cc",
#        data_file = '{output_path}/PRERECONSTRUCTED/{color}/{version}/ADC_batch{batch_idx}.stamp',
#        one_phe_files = "{output_path}/PEDESTAL/{color}/{version}/PIEDISTALLI_batch{batch_idx}.stamp"
#        #lambda wildcards: [
#        #    f"{output_path}/PEDESTAL/{wildcards.color}/{wildcards.version}/{wildcards.run}/pedestal_{n}.cfg"
#        #    for n in range(16)
#        #]
#
#    output:
#        output_filename = '{output_path}/RECONSTRUCTED/{color}/{version}/MURAVES_AnalyzedData_batch{batch_idx}.stamp',
#    shell: "g++ -std=c++20 {input.script_4} {input.script_3} {input.script_2} {input.script_1} {input.main_script} "
#           "-o 4_MainRecSof/MURAVES_reco_v2.exe "
#           "$(root-config --cflags --libs) -lSpectrum "
#           "-I/opt/conda/envs/muraves/include/python3.11 "
#            "-L/opt/conda/envs/muraves/lib -lpython3.11 &&"
#            "./4_MainRecSof/MURAVES_reco_v2.exe {wildcards.color} {wildcards.run} {wildcards.run}" ##NB: wildcard run has to deshappear





# Not used anymore
#rule stageout:
#    input:
#        lambda wildcards: os.path.join(SCRATCH, wildcards.subpath)
#    output:
#        os.path.join(PNFS, "{subpath}")
#    shell:
#        """
#        rsync -av {input} {output} &&
#        rm {input}
#        """




