configfile: 'config.yaml'
configfile: '../tag/requirements.yaml'

# IMPROVEMENTS:
# The number of boards and channel should go in another configuration file

#Function to convert runs of config file to list of runs
def parse_runs(run_str):
    runs = []
    for part in run_str.split(','):
        part = part.strip()
        if '-' in part:
            start, end = map(int, part.split('-'))
            runs.extend(range(start, end + 1))
        else:
            runs.append(int(part))
    return [str(r) for r in runs] 

runs = parse_runs(config['run']) # convert config file format into list of runs.

localrules: all

# Rule that tells the list of final outputs that must be produced by the flow
rule all:
    input:
        expand(
        '{path}/PARSED/{color}/{version}/{type}_run{run}.txt',
            path=config['data_path'],
            color=config['hodoscope'],
            version = config['version'],
            type=config['type'],
            run=runs
        )  

  
rule parse:
    input: 
        script='1_Parser/prep.py',
    params:
        #rawfile_path = '{path}/RAW_GZ/{color}',
        optional_input_files = ['{path}/RAW_GZ/{color}/SLOWCONTROL_run{run}.gz', '{path}/RAW_GZ/{color}/LOG_run{run}.gz', '{path}/RAW_GZ/{color}/CONTEGGI_run{run}.gz']

    output:
        output_filename = '{path}/PARSED/{color}/{version}/{type}_run{run}.txt',
        status_file = '{path}/PARSED/{color}/{version}/{type}_run{run}.json',
        log_file = '{path}/PARSED/{color}/{version}/{type}_run{run}.log'
    shell: "python {input.script} -i {params.optional_input_files} -t {wildcards.type} -r {wildcards.run} -o {output.output_filename} -l {output.log_file} -j {output.status_file}"



rule prereco:
    input:
        script = '2_PreRec/MakePedestalTree.py',
        file = '{path}/PARSED/{color}/{version}/{type}_run{run}.txt'
    params:
        nBoards = 16,
        nInfoBoard = 39,
        nChannels= 32
    output:
        output_filename = '{path}/PRERECONSTRUCTED/{color}/{version}/{type}_run{run}.root'
    shell: "python {input.script} -data {input.file} -r {wildcards.run} -type {wildcards.type} -info {params.nBoards} {params.nInfoBoard} {params.nChannels} -o {output.output_filename}"



rule pedestal_analysis:
    input:
        script = '3_PedAna/OnePhE_evaluator.py',
        file = '{path}/PRERECONSTRUCTED/{color}/{version}/PIEDISTALLI_run{run}.root'
    #params: # to be removed at next version
    #    number_of_runs = 1
    #    delta_around_central_runID = 0
    output:
        expand(
            "{{path}}/PEDESTAL/{{color}}/{{version}}/{{run}}/pedestal_{n}.cfg", n = range(16)
        )
    shell: "python {input.script} -data {input.file} -r {wildcards.run} -o {output}"



rule analyse:
    input:
        main_script = "4_MainRecSof/MURAVES_reco_v2.cpp",
        script_1 = "4_MainRecSof/ClusterLists.cc",
        script_2 =  "4_MainRecSof/EvaluateAngularCoordinates.cc",
        script_3 = "4_MainRecSof/ReadEvent.cc",
        script_4 = "4_MainRecSof/Tracking.cc",
        data_file = '{path}/PRERECONSTRUCTED/{color}/{version}/ADC_run{run}.root',
        one_phe_files = lambda wildcards: [
            f"{wildcards.path}/PEDESTAL/{wildcards.color}/{wildcards.version}/{wildcards.run}/pedestal_{n}.cfg"
            for n in range(16)
        ]

    output:
        output_filename = '{path}/RECONSTRUCTED/{color}/{version}/MURAVES_AnalyzedData_run{run}.root',
    shell: "g++ -std=c++20 {input.script_4} {input.script_3} {input.script_2} {input.script_1} {input.main_script} "
           "-o 4_MainRecSof/MURAVES_reco_v2.exe "
           "$(root-config --cflags --libs) -lSpectrum "
           "-I/opt/conda/envs/muraves/include/python3.11 "
            "-L/opt/conda/envs/muraves/lib -lpython3.11 &&"
            "./4_MainRecSof/MURAVES_reco_v2.exe {wildcards.color} {wildcards.run} {wildcards.run}"

